AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ApiKeyEmailTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'api-key'
          AttributeType: 'S'
        - AttributeName: 'email'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'api-key'
          KeyType: 'HASH'
        - AttributeName: 'email'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: 'apikey-email-table'
Outputs:
  ApiKeyEmailTableArn:
    Description: 'ARN of the ApiKeyEmailTable'
    Value: !GetAtt ApiKeyEmailTable.Arn
    Export:
      Name: ApiKeyEmailTableArn